name: fork-build
on:
  push:
    branches:
      - 'master'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  # 手动触发
  workflow_dispatch:
  # 每周日凌晨2点自动编译
  schedule:
    - cron: '0 2 * * 0'

permissions:
  actions: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-24.04
            compiler:
              CC: clang-18
              CXX: clang++-18
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.compiler.CC }}-modules
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - uses: ./.github/actions/linux-build
        with:
          CC: ${{ matrix.compiler.CC }}
          CXX: ${{ matrix.compiler.CXX }}
          modules: true
          pch: false
          maxerrors: 0
          keepgoing: true
